### PR TITLE
Revert "chore(deps): Bump dart_frog from 0.3.3 to 0.3.5 in /flutter_news_example/api"

### PR DESCRIPTION
**Pull request by kaiceyd**
Reverts flutter/news_toolkit#845

### CODE REVIEW

**Comment by valentinallavayol** [comment]
Hey @felangel ! @kaiceyd is reverting this merge because the initial dependabot PR that bumped this dependency (https://github.com/flutter/news_toolkit/pull/845) had your approval, so it was merged.

The thing is, flutter_localizations (which is inside flutter sdk) uses meta 1.8.0 and dart_ frog 0.3.4 depends on meta 1.9.0, so dependency solving fails unless we override the meta dependency in a lot of places, which is definitely not ideal.

What would be the best approach we should take here?

**Comment by marwfair** [comment]
> Hey @felangel ! @kaiceyd is reverting this merge because the initial dependabot PR that bumped this dependency (#845) had your approval, so it was merged.
> 
> The thing is, flutter_localizations (which is inside flutter sdk) uses meta 1.8.0 and dart_ frog 0.3.4 depends on meta 1.9.0, so dependency solving fails unless we override the meta dependency in a lot of places, which is definitely not ideal.
> 
> What would be the best approach we should take here?

Is there any harm with keeping dart_frog on the older version for now?

**Comment by valentinallavayol** [comment]
> > Hey @felangel ! @kaiceyd is reverting this merge because the initial dependabot PR that bumped this dependency (#845) had your approval, so it was merged.
> > The thing is, flutter_localizations (which is inside flutter sdk) uses meta 1.8.0 and dart_ frog 0.3.4 depends on meta 1.9.0, so dependency solving fails unless we override the meta dependency in a lot of places, which is definitely not ideal.
> > What would be the best approach we should take here?
> 
> Is there any harm with keeping dart_frog on the older version for now?

The updates from version 0.3.3 to version 0.3.5 they've made are quite minor, so I really don't think so. This could end up being a problem with future dart_frog updates though

**Review by marwfair — APPROVED** [review]
LGTM!

**Review by scarletteliza — APPROVED** [review]

**Pull request merged**
