### PR TITLE
Remove GoogleService-Info.plist copy in iOS project

### PR DESCRIPTION
**Pull request by jmagman**
## Description

The development GoogleService-Info.plist is always being copied into the Xcode bundle resources, even during a production flavor build:

Screenshot 2024-01-04 at 6 03 32 PM
Screenshot 2024-01-04 at 6 03 21 PM

When the template is generated with only a production flavor, the build fails:
```
Error (Xcode): Build input file cannot be found: ios/Runner/development/GoogleService-Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?
```

Delete that copy in favor of the `Copy GoogleServices-Info.plist` build phase script, which already handles copying the right flavor variant.

Fixes https://github.com/flutter/flutter/issues/140281

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by jmagman** [comment]
@MacarenaSantos I'm not sure if the example app is the right place to fix this since I don't know how the template generation works.  
Also, I'm not sure how to test this.  It reproduces if you generate the template with only the production flavor and then build the app.  Can you point me in the right direction?

**Comment by zoeyfan** [comment]
Thank you @jmagman 
@MacarenaSantos would you please bubble this to the eng team to review and merge? Thank you!

**Review by valentinallavayol — APPROVED** [review]
LGTM!

**Comment by valentinallavayol** [comment]
@jmagman Once the PR gets merged, this change will be propagated to the template generation files (that are allocated on the `templates` branch) with another PR that automatically creates once this PR is merged to `main`.

**Pull request merged**
